travis:
  secure:
    BINSTAR_TOKEN: ATJQ0B6bkBcEE61M1ywwiljwB/emX0p4JhXlvkZrlviQwNNp5y4oLYpc4PTcJoceTOzbeu2QEwejEjYfxsTbKetIDDxUx0+cwLVmvxALvzzTx69got7WlMhG/P0CI1bx/tKGSjI8lXipDeZ3LMpG/tVbSWvVlonWpNIY6OM9/QcFdQRHORWfh6fmJHpGpRexJZpE5Bb63WSiXM9rmELHvQ4sC3KvqQID7idHs8/AGpL3dthnh7yvlit2yfCrkLAPHUndua65VFZsRYJpLVQtnpa2bB3u5vKJdHDpLhsYJ7LHdZe6uYYnOEspcEwEYrCJ8EjSHQrnOs2chtLwMkYtnmYHi8SOoGUThnG3KDlzUf0zOOvABQ0/56V/9ESiLb0yP13Yqrmz07LPUrsDVXEnTV8riPbg9xWs9oKB3vdXgeAimsGUiuynUZJCuTOXvY3ea4oimjqJczm8t9TkXzQoT3HVr8QTmAs2YKSB6+txdvplvx/7GZiSbK4xV6zGhOS/IoK56fZGCnupaWtLJWZqaEN6E+qu7FY5zGm18jkpnSZCLpae1Us5rVsyI8DwVZFeDs+Fu04/pbqvgmngmm4i9eYq0LCPrBGVqvLA+TslWm9evSpEhT5BGJgdK6MmufEjYoECNI0yjN6Nhdf3aWxJ8IUiu6MPmQgDSlsicbpj17c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
