travis:
  secure:
    BINSTAR_TOKEN: YhOccJWemEarUOehFtCuGz9gevRmyoUlOk+KS0axFQ6tsHmMNdekbpDWwAvo9M6Ev4xIJBzkngRKFRarwJivdw4ugzlyBpGFDkiqfA5CozOU45t4HRsH1LqzkO5p+FTCfWgDJjO6JZjqRwtMA2VNXg1lZzU/GqefOtuJl6Bwg6f91sdpUYet+4tidWxYZVw1mmm+HNTxNtGpHcT9HZA9agjuq4xSKc7NkQbhAVPrttQuCU1O1DB6N8WTGtF508z5kgZe7S1ADgXQOQnvzKQsit3HMyyrXgioI466vNhdz+DyfEWRSWF9FAWgfBSleT9hBpqkNVn+m92snNWn9Je1c7fTjyjUfwirLTl5/dKd82dJOxREJS8GI5uBPgK9GBnhs6o+1P6+tBzvRSnbuCHkBQ/fVKvg6THAh2wydvk7bi2J5cQM+p5l/nJ2AV6kSscWZpnMgjrit0yL82oz0PfHr3p7GcTe9MS9ttKeZEpQLBRIqfDn+wGAxM1+E/dvGJ13labHPVroAIL1rXSmq1BtqZ5NqVzX8l3YM+OLVELIKixPiE6vN5q3EufHiwVnEbz3UWUJofPUvq5TNeSE+XIiaPbX39f2DMYyRgwjmAc5bwdFbKTaNHyI/Wtr1oPkmDsvoQd5am5NfwByP7c1Uujbcxzme1mLf/D3nLJcQOn//X4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
