travis:
  secure:
    BINSTAR_TOKEN: kaf5FxOkztdk4OK/gYCj1KFnHRLgb5xcpn1dWi6xQwM8mvSaO9PJF5yuB8j0SHAd1avrkO4FWeJFF2rMK523EH91xwI/W5ztpMvZukScnU6tFkz1l28P8J7OGVrQHrSrYjx6Obm5XMh88dOkZvo4EsmB3h7DhAePiKXevNFKxiBdkbOGXvcfzG/0IDgGY9EEDgWjaRNM/BrbJ1QCwFMXYSMDzWVVxXk2sa9SFpXRGQ1znUvu8Rg7eJ80DQugSBltnoIZ7M3oN9CwqaNThRce4Y1rBXGZmD1vyjNgd3rfrByJs2rNTBghtdsTbMD6h7DADdMCPWsIXBLicZ+avFaGUQ/nEyjxuX4pdY33TtX4n8WkqTuvFx6MCABwIOk3WanTIR+KYXW1F4Plzh2V1K7QqxuMpjg0d2SrMxiCx/zGbPvEldDVQZAX8CtwbrYmVOcsuPk3HNCCQkQWAroqLzyKW3D32wODeAxf1AS7cDlLUuitAaD0gVkpdvCxesovYoA/Pp/uPGW5ob7VoDifIr+dWsVOsIliwYPA9wYZHllzDM778uMZZZndTfy83Qhus7WkSYvYIGphRm2qYgskYlqgfZfgT7TCAZNOUgHBqhhSIJ1QUAdnVRGj6cyx8KKJ7ofywcQJaaoOSHj18XSPOUmoN5Ylsesu+dDlmxNWfMY/4DM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
